### ISSUE TITLE
App crashes when Assistant/Spark are connected

### ISSUE THREAD

**Issue by mykeln** [mavicBreak/DroneZBreak#2]
[dronezbreaklog.txt](https://github.com/mavicBreak/DroneZBreak/files/1232690/dronezbreaklog.txt)

Everything gets connected and runs.

App crashes immediately after it gets past "Reading Drone model"

I see it display the firmware for half a second, then it immediately quits.

**Comment by mavicBreak** [comment]
I am working on it. Can you please try what happens if you use DJI Assistant 1.0.9? Which OSX?

And just to make sure when it quits do you see "Reading Drone model" or something like "DJI Spark  | SN: 5GBFJFIKDNN  |  Firmware: 01.00.0300"? Even if it appears only for half a second matters.

**Comment by mavicBreak** [comment]
v0.3 is out. If it doesn't solve your issue please use the new Debug log function and send me the log. After application has started but before connecting your Spark: press CMD + D which activates debug logging. DZB_log.txt will be created on your desktop. After the crash pls forward this log to me.

**Comment by mykeln** [comment]
Latest version says it can't be opened because it's damaged or incomplete
(when I try to run the app from a fresh download/unzip)


Myke

**Comment by mavicBreak** [comment]
You are not downloading it correctly or you are not unzipping the file before use. Please check for other closed issues here, it was discussed multiple times. Thank you!
