### ISSUE TITLE
FTP Error when Flash Firmware

### ISSUE THREAD

**Issue by fly-focus** [mavicBreak/DroneZBreak#7]
Mavic pro Using the latest version 0.7,when i click Flash Firmware,i got warning message

Error occured during FTP upload. Details: Optional(Error Domain=kCFErrorDomainCFNetwork Code=200 "(null)" UserInfo={kCFFTPStatusCodeKey=421})

**Comment by fly-focus** [comment]
![5243](https://user-images.githubusercontent.com/29201540/29992747-8123ad3c-8fd5-11e7-9732-f31b40487f5c.png)

**Comment by dronething** [comment]
@fly-focus, what firmware do you use? What osx do you use? What mac do you use? Once you open the app you can push debug button and later you can send DZB_log from your desktop to developer.  AFAIK, only mac mini has error on ftp

**Comment by nicdive** [comment]
Hi, 
Same error here trying to downgrade from 1000 to 700 with version 0.7, macbook high sierra.

**Comment by mavicBreak** [comment]
Initial FTP connection is not established in your case. Usually it works if you disconnect USB cable, wait 10 seconds and reconnect, or try to connect it to another USB port.

If it does not help:
Make sure Assistant is NOT running, try to restart DroneZBreak or even restart Mac.
After turning on Mavic and before flashing wait at least one minute to let it fully boot up. Try to use another USB port if still doesn't work.

**Comment by dronething** [comment]
@fly-focus and @mavicBreak I got that error using latest 0.8 version but I thought it happened because usb not connected well. so I disconnect the cable, reopen DZB, now to make sure usb well connect I open Assistant 2 when DZB asked me, just to confirm assistant detect my drone and I close Assistant. Then I go to firmware upgrade button and it goes well. no need to restart Mac since I also watch Netflix by downgrading my mavic. ;)

**Comment by fly-focus** [comment]
@dronething @mavicBreak @nicdive  I find a solution.i can‘t open the FTP folder ftp://192.168.42.2 sometimes.
I don't know why,I have already closed my firewall,and i have wait at least 5 minutes.

Connect the Mavic, try to open ftp://192.168.42.2 by safari,the beginning of a few times will be wrong,3 or 5 times later,I can open the folder.Then disconnect the FTP .
![0103243](https://user-images.githubusercontent.com/29201540/30004854-e4d3649c-9108-11e7-8828-4b265dcb559d.png)
Now try to upgrade,haha,its works well.

**Comment by dronething** [comment]
@fly-focus , i recommend you download again latest uploaded by @mavicbreak and test it out.

**Comment by nicdive** [comment]
I successfully downgrade my RC from 900 to 700. For my aircraft and goggles from 1000 to 700
, I tried 10 times without success, on a macbook high Sierra and on a MacBook Air Sierra. same error occurs, log attached? thanks for your help.

[DZB_log.txt](https://github.com/mavicBreak/DroneZBreak/files/1274233/DZB_log.txt)
